### ISSUE TITLE
Use in symfony 1.4

### ISSUE THREAD

**Issue by tristanbes** [francisbesset/sfContextBundle#7]
Hi

I wanted to thank devs who developped this bundle which I used on a Symfony2 projet because someone told me it was more optimized that `$this->getContainer()`

I was wondering, i'm currently working on a symfony1.4 project and i want to backport this bundle on symfony1.4.

I was thinking of each time i call sfContext, instanciate a new Symfony2 kernel, and via pimple, inject the whole kernel in symfony 1.4 in order to replace & overrwrite the already existent method..... but it's only a thought.

Regards ;-)

**Comment by francisbesset** [comment]
Hi @tristanbes!
Symfony 1 has already the sfContext because it's the best solution.

In Symfony2, the sfContext does not incorporate in Framework because the core team work to solve security problems of Symfony2 and the sfContext has been forgotten.

I fortunately provides a powerful and effective solution to solve the problem.

**Comment by tristanbes** [comment]
Ok ! Thanks for the clarification :p [/troll off]

![](http://cdn.memegenerator.net/instances/400x/35418413.jpg)

**Comment by lyrixx** [comment]
I think we can safely close this issue.

**Comment by tristanbes** [comment]
not sure... I still need this inside all my apps :trollface:
